//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-01-28 - 12:02:24
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Itsyazilim.Web.Domain
{
    [DataContract()]
    public partial class C_OrderStartPositionsDTO
    {
        [DataMember()]
        public Int64 OrderStartPositionId { get; set; }

        [DataMember()]
        public Int64 OrderId { get; set; }

        [DataMember()]
        public Int16 CountyId { get; set; }

        public C_OrderStartPositionsDTO()
        {
        }

        public C_OrderStartPositionsDTO(Int64 orderStartPositionId, Int64 orderId, Int16 countyId)
        {
			this.OrderStartPositionId = orderStartPositionId;
			this.OrderId = orderId;
			this.CountyId = countyId;
        }
    }
}
