//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-01-28 - 12:02:23
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Itsyazilim.Web.Domain
{
    [DataContract()]
    public partial class C_OrderEndPositionsDTO
    {
        [DataMember()]
        public Int64 OrderEndPositionId { get; set; }

        [DataMember()]
        public Int64 OrderId { get; set; }

        [DataMember()]
        public Int16 CountyId { get; set; }

        public C_OrderEndPositionsDTO()
        {
        }

        public C_OrderEndPositionsDTO(Int64 orderEndPositionId, Int64 orderId, Int16 countyId)
        {
			this.OrderEndPositionId = orderEndPositionId;
			this.OrderId = orderId;
			this.CountyId = countyId;
        }
    }
}
