//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-01-28 - 12:02:24
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Itsyazilim.Web.Domain
{
    [DataContract()]
    public partial class DefLocationCountryDTO
    {
        [DataMember()]
        public Byte CountryId { get; set; }

        [DataMember()]
        public String Name { get; set; }

        public DefLocationCountryDTO()
        {
        }

        public DefLocationCountryDTO(Byte countryId, String name)
        {
			this.CountryId = countryId;
			this.Name = name;
        }
    }
}
