//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-01-28 - 12:02:24
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Itsyazilim.Web.Domain
{
    [DataContract()]
    public partial class DefLocationCountyDTO
    {
        [DataMember()]
        public Int32 CountyId { get; set; }

        [DataMember()]
        public String Name { get; set; }

        [DataMember()]
        public Int16 CityId { get; set; }

        [DataMember()]
        public Int16 LocalCode { get; set; }

        public DefLocationCountyDTO()
        {
        }

        public DefLocationCountyDTO(Int32 countyId, String name, Int16 cityId, Int16 localCode)
        {
			this.CountyId = countyId;
			this.Name = name;
			this.CityId = cityId;
			this.LocalCode = localCode;
        }
    }
}
