//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-01-28 - 12:02:24
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Itsyazilim.Web.Domain
{
    [DataContract()]
    public partial class DefLocationRegionDTO
    {
        [DataMember()]
        public Int16 RegionId { get; set; }

        [DataMember()]
        public String Name { get; set; }

        [DataMember()]
        public Byte CountryId { get; set; }

        [DataMember()]
        public Byte LocalCode { get; set; }

        public DefLocationRegionDTO()
        {
        }

        public DefLocationRegionDTO(Int16 regionId, String name, Byte countryId, Byte localCode)
        {
			this.RegionId = regionId;
			this.Name = name;
			this.CountryId = countryId;
			this.LocalCode = localCode;
        }
    }
}
