//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-01-28 - 12:02:24
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Itsyazilim.Web.Domain
{
    [DataContract()]
    public partial class DefOrderTypeDTO
    {
        [DataMember()]
        public Byte OrderTypeId { get; set; }

        [DataMember()]
        public String OrderTypeName { get; set; }

        public DefOrderTypeDTO()
        {
        }

        public DefOrderTypeDTO(Byte orderTypeId, String orderTypeName)
        {
			this.OrderTypeId = orderTypeId;
			this.OrderTypeName = orderTypeName;
        }
    }
}
