//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-01-28 - 12:02:25
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Itsyazilim.Web.Domain
{
    [DataContract()]
    public partial class DefProductTypeDTO
    {
        [DataMember()]
        public Int16 ProductTypeId { get; set; }

        [DataMember()]
        public String ProductTypeName { get; set; }

        [DataMember()]
        public Int32 CreatedBy { get; set; }

        [DataMember()]
        public DateTime CreatedOn { get; set; }

        [DataMember()]
        public Boolean IsDeleted { get; set; }

        [DataMember()]
        public Nullable<Int32> DeletedBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> DeletedOn { get; set; }

        public DefProductTypeDTO()
        {
        }

        public DefProductTypeDTO(Int16 productTypeId, String productTypeName, Int32 createdBy, DateTime createdOn, Boolean isDeleted, Nullable<Int32> deletedBy, Nullable<DateTime> deletedOn)
        {
			this.ProductTypeId = productTypeId;
			this.ProductTypeName = productTypeName;
			this.CreatedBy = createdBy;
			this.CreatedOn = createdOn;
			this.IsDeleted = isDeleted;
			this.DeletedBy = deletedBy;
			this.DeletedOn = deletedOn;
        }
    }
}
