//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-01-28 - 12:02:26
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Itsyazilim.Web.Domain
{
    [DataContract()]
    public partial class FirmDTO
    {
        [DataMember()]
        public Int32 FirmId { get; set; }

        [DataMember()]
        public String FirmName { get; set; }

        [DataMember()]
        public Int32 CountyId { get; set; }

        [DataMember()]
        public String Address { get; set; }

        [DataMember()]
        public String Phone1 { get; set; }

        [DataMember()]
        public String Phone2 { get; set; }

        [DataMember()]
        public String Fax { get; set; }

        [DataMember()]
        public String MobilePhone { get; set; }

        [DataMember()]
        public String Email { get; set; }

        [DataMember()]
        public String WebSite { get; set; }

        [DataMember()]
        public String TaxOffice { get; set; }

        [DataMember()]
        public String TaxNo { get; set; }

        [DataMember()]
        public Int32 CreatedBy { get; set; }

        [DataMember()]
        public Boolean IsApproved { get; set; }

        [DataMember()]
        public Nullable<Int32> ApprovedBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> ApprovedOn { get; set; }

        [DataMember()]
        public DateTime CreatedOn { get; set; }

        [DataMember()]
        public Nullable<DateTime> UpdatedOn { get; set; }

        public FirmDTO()
        {
        }

        public FirmDTO(Int32 firmId, String firmName, Int32 countyId, String address, String phone1, String phone2, String fax, String mobilePhone, String email, String webSite, String taxOffice, String taxNo, Int32 createdBy, Boolean isApproved, Nullable<Int32> approvedBy, Nullable<DateTime> approvedOn, DateTime createdOn, Nullable<DateTime> updatedOn)
        {
			this.FirmId = firmId;
			this.FirmName = firmName;
			this.CountyId = countyId;
			this.Address = address;
			this.Phone1 = phone1;
			this.Phone2 = phone2;
			this.Fax = fax;
			this.MobilePhone = mobilePhone;
			this.Email = email;
			this.WebSite = webSite;
			this.TaxOffice = taxOffice;
			this.TaxNo = taxNo;
			this.CreatedBy = createdBy;
			this.IsApproved = isApproved;
			this.ApprovedBy = approvedBy;
			this.ApprovedOn = approvedOn;
			this.CreatedOn = createdOn;
			this.UpdatedOn = updatedOn;
        }
    }
}
