//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-01-28 - 12:02:27
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Itsyazilim.Web.Domain
{
    [DataContract()]
    public partial class LogSystemMailSendDTO
    {
        [DataMember()]
        public Int64 LogId { get; set; }

        [DataMember()]
        public String Email { get; set; }

        [DataMember()]
        public String ErrorMessage { get; set; }

        [DataMember()]
        public String PageName { get; set; }

        [DataMember()]
        public String IP { get; set; }

        [DataMember()]
        public DateTime CreatedOn { get; set; }

        public LogSystemMailSendDTO()
        {
        }

        public LogSystemMailSendDTO(Int64 logId, String email, String errorMessage, String pageName, String iP, DateTime createdOn)
        {
			this.LogId = logId;
			this.Email = email;
			this.ErrorMessage = errorMessage;
			this.PageName = pageName;
			this.IP = iP;
			this.CreatedOn = createdOn;
        }
    }
}
