//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-01-28 - 12:02:28
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Itsyazilim.Web.Domain
{
    [DataContract()]
    public partial class MapFirmToUserDTO
    {
        [DataMember()]
        public Int64 MapId { get; set; }

        [DataMember()]
        public Int32 FirmId { get; set; }

        [DataMember()]
        public Int32 UserId { get; set; }

        [DataMember()]
        public Boolean IsAdmin { get; set; }

        [DataMember()]
        public Boolean IsActive { get; set; }

        [DataMember()]
        public DateTime CreatedOn { get; set; }

        public MapFirmToUserDTO()
        {
        }

        public MapFirmToUserDTO(Int64 mapId, Int32 firmId, Int32 userId, Boolean isAdmin, Boolean isActive, DateTime createdOn)
        {
			this.MapId = mapId;
			this.FirmId = firmId;
			this.UserId = userId;
			this.IsAdmin = isAdmin;
			this.IsActive = isActive;
			this.CreatedOn = createdOn;
        }
    }
}
