//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-01-28 - 12:02:28
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Itsyazilim.Web.Domain
{
    [DataContract()]
    public partial class MembershipPasswordRenewalDTO
    {
        [DataMember()]
        public Int64 RenewalId { get; set; }

        [DataMember()]
        public String Email { get; set; }

        [DataMember()]
        public String ActivateCode { get; set; }

        [DataMember()]
        public String IP { get; set; }

        [DataMember()]
        public DateTime CreatedOn { get; set; }

        public MembershipPasswordRenewalDTO()
        {
        }

        public MembershipPasswordRenewalDTO(Int64 renewalId, String email, String activateCode, String iP, DateTime createdOn)
        {
			this.RenewalId = renewalId;
			this.Email = email;
			this.ActivateCode = activateCode;
			this.IP = iP;
			this.CreatedOn = createdOn;
        }
    }
}
