//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-01-28 - 12:02:28
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Itsyazilim.Web.Domain
{
    [DataContract()]
    public partial class MembershipDTO
    {
        [DataMember()]
        public Int32 UserId { get; set; }

        [DataMember()]
        public String Email { get; set; }

        [DataMember()]
        public String Password { get; set; }

        [DataMember()]
        public String Name { get; set; }

        [DataMember()]
        public String Surname { get; set; }

        [DataMember()]
        public Byte StatusId { get; set; }

        [DataMember()]
        public Byte RoleId { get; set; }

        [DataMember()]
        public Boolean IsDeleted { get; set; }

        [DataMember()]
        public Nullable<Int32> FailedPasswordAttemptCount { get; set; }

        [DataMember()]
        public Nullable<DateTime> LastLoginDate { get; set; }

        [DataMember()]
        public Nullable<DateTime> LastPasswordChangeDate { get; set; }

        [DataMember()]
        public String Comment { get; set; }

        [DataMember()]
        public Nullable<DateTime> VerifyOn { get; set; }

        [DataMember()]
        public String IP { get; set; }

        [DataMember()]
        public DateTime CreatedOn { get; set; }

        [DataMember()]
        public Nullable<DateTime> UpdatedOn { get; set; }

        public MembershipDTO()
        {
        }

        public MembershipDTO(Int32 userId, String email, String password, String name, String surname, Byte statusId, Byte roleId, Boolean isDeleted, Nullable<Int32> failedPasswordAttemptCount, Nullable<DateTime> lastLoginDate, Nullable<DateTime> lastPasswordChangeDate, String comment, Nullable<DateTime> verifyOn, String iP, DateTime createdOn, Nullable<DateTime> updatedOn)
        {
			this.UserId = userId;
			this.Email = email;
			this.Password = password;
			this.Name = name;
			this.Surname = surname;
			this.StatusId = statusId;
			this.RoleId = roleId;
			this.IsDeleted = isDeleted;
			this.FailedPasswordAttemptCount = failedPasswordAttemptCount;
			this.LastLoginDate = lastLoginDate;
			this.LastPasswordChangeDate = lastPasswordChangeDate;
			this.Comment = comment;
			this.VerifyOn = verifyOn;
			this.IP = iP;
			this.CreatedOn = createdOn;
			this.UpdatedOn = updatedOn;
        }
    }
}
