//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/02/03 - 22:39:19
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Itsyazilim.Web.Domain
{
    [DataContract()]
    public partial class MemeberRoleMappingDTO
    {
        [DataMember()]
        public Int32 RoleMappingId { get; set; }

        [DataMember()]
        public Nullable<Int32> RoleId { get; set; }

        [DataMember()]
        public Nullable<Int32> UserId { get; set; }

        [DataMember()]
        public Int32 Membership_UserId { get; set; }

        [DataMember()]
        public Int32 Role_RoleId { get; set; }

        public MemeberRoleMappingDTO()
        {
        }

        public MemeberRoleMappingDTO(Int32 roleMappingId, Nullable<Int32> roleId, Nullable<Int32> userId, Int32 membership_UserId, Int32 role_RoleId)
        {
			this.RoleMappingId = roleMappingId;
			this.RoleId = roleId;
			this.UserId = userId;
			this.Membership_UserId = membership_UserId;
			this.Role_RoleId = role_RoleId;
        }
    }
}
