//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/02/03 - 22:39:19
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Itsyazilim.Web.Domain
{
    [DataContract()]
    public partial class MemberRoleMappingDTO
    {
        [DataMember()]
        public Int32 RoleMappingId { get; set; }

        [DataMember()]
        public Int32 RoleId { get; set; }

        [DataMember()]
        public Int32 MemberId { get; set; }

        [DataMember()]
        public Int32 Membership_UserId { get; set; }

        [DataMember()]
        public Int32 Role_RoleId { get; set; }

        public string RoleName { get; set; }
        public string MemberName { get; set; }

        public List<RoleDTO> RoleList { get; set; }
        public List<MembershipDTO> MemberList { get; set; }

       
    }
}
