//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/02/03 - 22:39:20
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Itsyazilim.Web.Domain.Resources;

namespace Itsyazilim.Web.Domain
{
    [DataContract()]
    public partial class ModuleRoleMappingDTO : CommonModel
    {
        [DataMember()]
        public Int32 ModuleRoleMappingId { get; set; }

        [DataMember()]
        [Required(ErrorMessageResourceName = "valRequiredSelectRole", ErrorMessageResourceType = typeof(ItsyazilimWebResources))]
        public Int32 RoleId { get; set; }

        [DataMember()]
        [Required(ErrorMessageResourceName = "valRequiredSelectModule", ErrorMessageResourceType = typeof(ItsyazilimWebResources))]
        public Int32 ModuleId { get; set; }

        [DataMember()]
        public Int32 Module_ModuleId { get; set; }

        [DataMember()]
        public Int32 Role_RoleId { get; set; }

        public string ModuleName { get; set; }

        public string RoleName { get; set; }

        public List<RoleDTO> RoleList { get; set; }

        public List<ModuleDTO> ModuleList { get; set; }
    }
}
