//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/02/03 - 22:39:20
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Itsyazilim.Web.Domain
{
    [DataContract()]
    public partial class ModuleRoleMappingDTO
    {
        [DataMember()]
        public Int32 ModuleRoleMappingId { get; set; }

        [DataMember()]
        public Nullable<Int32> RoleId { get; set; }

        [DataMember()]
        public Nullable<Int32> ModuleId { get; set; }

        [DataMember()]
        public Int32 Module_ModuleId { get; set; }

        [DataMember()]
        public Int32 Role_RoleId { get; set; }

        public string ModuleName { get; set; }

        public string RoleName { get; set; }
    }
}
