//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-01-28 - 12:02:29
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Itsyazilim.Web.Domain
{
    [DataContract()]
    public partial class OrderDTO
    {
        [DataMember()]
        public Int64 OrderId { get; set; }

        [DataMember()]
        public Int32 FirmId { get; set; }

        [DataMember()]
        public Int32 UserId { get; set; }

        [DataMember()]
        public Byte OrderTypeId { get; set; }

        [DataMember()]
        public Nullable<Byte> VehicleTypeId { get; set; }

        [DataMember()]
        public Nullable<DateTime> DepartureDate { get; set; }

        [DataMember()]
        public Nullable<TimeSpan> DepartureTime { get; set; }

        [DataMember()]
        public Byte DepartureDateType { get; set; }

        [DataMember()]
        public Nullable<DateTime> ArrivalDate { get; set; }

        [DataMember()]
        public Nullable<Byte> ArrivalDateType { get; set; }

        [DataMember()]
        public String Comment { get; set; }

        [DataMember()]
        public Boolean IsActive { get; set; }

        [DataMember()]
        public DateTime CreatedOn { get; set; }

        [DataMember()]
        public Nullable<DateTime> UpdatedOn { get; set; }

        public OrderDTO()
        {
        }

        public OrderDTO(Int64 orderId, Int32 firmId, Int32 userId, Byte orderTypeId, Nullable<Byte> vehicleTypeId, Nullable<DateTime> departureDate, Nullable<TimeSpan> departureTime, Byte departureDateType, Nullable<DateTime> arrivalDate, Nullable<Byte> arrivalDateType, String comment, Boolean isActive, DateTime createdOn, Nullable<DateTime> updatedOn)
        {
			this.OrderId = orderId;
			this.FirmId = firmId;
			this.UserId = userId;
			this.OrderTypeId = orderTypeId;
			this.VehicleTypeId = vehicleTypeId;
			this.DepartureDate = departureDate;
			this.DepartureTime = departureTime;
			this.DepartureDateType = departureDateType;
			this.ArrivalDate = arrivalDate;
			this.ArrivalDateType = arrivalDateType;
			this.Comment = comment;
			this.IsActive = isActive;
			this.CreatedOn = createdOn;
			this.UpdatedOn = updatedOn;
        }
    }
}
