//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-01-28 - 12:02:29
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Itsyazilim.Web.Domain
{
    [DataContract()]
    public partial class OrderProductPropertyDTO
    {
        [DataMember()]
        public Int64 OrderProductPropertiesId { get; set; }

        [DataMember()]
        public Nullable<Int64> OrderDetailId { get; set; }

        [DataMember()]
        public Nullable<Int16> ProductPropertyId { get; set; }

        public OrderProductPropertyDTO()
        {
        }

        public OrderProductPropertyDTO(Int64 orderProductPropertiesId, Nullable<Int64> orderDetailId, Nullable<Int16> productPropertyId)
        {
			this.OrderProductPropertiesId = orderProductPropertiesId;
			this.OrderDetailId = orderDetailId;
			this.ProductPropertyId = productPropertyId;
        }
    }
}
