//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/02/03 - 22:39:22
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Itsyazilim.Web.Domain
{
    [DataContract()]
    public partial class RoleDTO
    {
        [DataMember()]
        public Int32 RoleId { get; set; }

        [DataMember()]
        public String RoleName { get; set; }

        [DataMember()]
        public String Description { get; set; }

        [DataMember()]
        public List<Int32> MemeberRoleMappings_RoleMappingId { get; set; }

        [DataMember()]
        public List<Int32> ModuleRoleMappings_ModuleRoleMappingId { get; set; }

        public RoleDTO()
        {
        }

        public RoleDTO(Int32 roleId, String roleName, String description, List<Int32> memeberRoleMappings_RoleMappingId, List<Int32> moduleRoleMappings_ModuleRoleMappingId)
        {
			this.RoleId = roleId;
			this.RoleName = roleName;
			this.Description = description;
			this.MemeberRoleMappings_RoleMappingId = memeberRoleMappings_RoleMappingId;
			this.ModuleRoleMappings_ModuleRoleMappingId = moduleRoleMappings_ModuleRoleMappingId;
        }
    }
}
