//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itsyazilim.Web.SQLServer.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogSystemMailSend
    {
        public long LogId { get; set; }
        public string Email { get; set; }
        public string ErrorMessage { get; set; }
        public string PageName { get; set; }
        public string IP { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
