//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itsyazilim.Web.SQLServer.ORM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LtsyazilimDatabaseEntities : DbContext
    {
        public LtsyazilimDatabaseEntities()
            : base("name=LtsyazilimDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_OrderEndPositions> C_OrderEndPositions { get; set; }
        public virtual DbSet<C_OrderStartPositions> C_OrderStartPositions { get; set; }
        public virtual DbSet<DefLocationCity> DefLocationCities { get; set; }
        public virtual DbSet<DefLocationCounty> DefLocationCounties { get; set; }
        public virtual DbSet<DefLocationCountry> DefLocationCountries { get; set; }
        public virtual DbSet<DefLocationRegion> DefLocationRegions { get; set; }
        public virtual DbSet<DefOrderType> DefOrderTypes { get; set; }
        public virtual DbSet<DefProductPackage> DefProductPackages { get; set; }
        public virtual DbSet<DefProductProperty> DefProductProperties { get; set; }
        public virtual DbSet<DefProductType> DefProductTypes { get; set; }
        public virtual DbSet<DefProductUnit> DefProductUnits { get; set; }
        public virtual DbSet<DefVehicleType> DefVehicleTypes { get; set; }
        public virtual DbSet<Firm> Firms { get; set; }
        public virtual DbSet<LogMembershipCheckPasswordRenewalCode> LogMembershipCheckPasswordRenewalCodes { get; set; }
        public virtual DbSet<LogMembershipLogin> LogMembershipLogins { get; set; }
        public virtual DbSet<LogMembershipRegisterCheckCode> LogMembershipRegisterCheckCodes { get; set; }
        public virtual DbSet<LogMembershipRegisterReSendCode> LogMembershipRegisterReSendCodes { get; set; }
        public virtual DbSet<LogMembershipSendPasswordRenewalCode> LogMembershipSendPasswordRenewalCodes { get; set; }
        public virtual DbSet<LogSystemMailSend> LogSystemMailSends { get; set; }
        public virtual DbSet<MapFirmToUser> MapFirmToUsers { get; set; }
        public virtual DbSet<MemberRoleMapping> MemberRoleMappings { get; set; }
        public virtual DbSet<MemberRole> MemberRoles { get; set; }
        public virtual DbSet<Membership> Memberships { get; set; }
        public virtual DbSet<MembershipPasswordRenewal> MembershipPasswordRenewals { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<ModuleRoleMapping> ModuleRoleMappings { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<OrderProductProperty> OrderProductProperties { get; set; }
        public virtual DbSet<OrderRoute> OrderRoutes { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
    
        public virtual ObjectResult<AdministratorSelectFirmDetails_Result> AdministratorSelectFirmDetails(Nullable<int> firmId)
        {
            var firmIdParameter = firmId.HasValue ?
                new ObjectParameter("FirmId", firmId) :
                new ObjectParameter("FirmId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AdministratorSelectFirmDetails_Result>("AdministratorSelectFirmDetails", firmIdParameter);
        }
    
        public virtual ObjectResult<AdministratorSelectFirms_Result> AdministratorSelectFirms()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AdministratorSelectFirms_Result>("AdministratorSelectFirms");
        }
    
        public virtual ObjectResult<AdministratorSelectUnApprovedFirmDetails_Result> AdministratorSelectUnApprovedFirmDetails(Nullable<int> firmId)
        {
            var firmIdParameter = firmId.HasValue ?
                new ObjectParameter("FirmId", firmId) :
                new ObjectParameter("FirmId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AdministratorSelectUnApprovedFirmDetails_Result>("AdministratorSelectUnApprovedFirmDetails", firmIdParameter);
        }
    
        public virtual ObjectResult<AdministratorSelectUnapprovedFirms_Result> AdministratorSelectUnapprovedFirms()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AdministratorSelectUnapprovedFirms_Result>("AdministratorSelectUnapprovedFirms");
        }
    
        public virtual ObjectResult<ManageSelectCountyListForTreeView_Result> ManageSelectCountyListForTreeView()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ManageSelectCountyListForTreeView_Result>("ManageSelectCountyListForTreeView");
        }
    }
}
