//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itsyazilim.Web.SQLServer.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberRoleMapping
    {
        public int RoleMappingId { get; set; }
        public int RoleId { get; set; }
        public int MemberId { get; set; }
    
        public virtual Membership Membership { get; set; }
        public virtual Role Role { get; set; }
    }
}
