//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itsyazilim.Web.SQLServer.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.MemberRoleMappings = new HashSet<MemberRoleMapping>();
            this.ModuleRoleMappings = new HashSet<ModuleRoleMapping>();
        }
    
        public int RoleId { get; set; }
        public string RoleName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<MemberRoleMapping> MemberRoleMappings { get; set; }
        public virtual ICollection<ModuleRoleMapping> ModuleRoleMappings { get; set; }
    }
}
