//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itsyazilim.Web.UI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_OrderStartPositions
    {
        public long OrderStartPositionId { get; set; }
        public long OrderId { get; set; }
        public short CountyId { get; set; }
    }
}
