//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itsyazilim.Web.UI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefLocationCountries
    {
        public byte CountryId { get; set; }
        public string Name { get; set; }
    }
}
