//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itsyazilim.Web.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ItsyazilimWebResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ItsyazilimWebResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Itsyazilim.Web.Domain.Resources.ItsyazilimWebResources", typeof(ItsyazilimWebResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Activation.
        /// </summary>
        public static string lblAccountActivation {
            get {
                return ResourceManager.GetString("lblAccountActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account created with this email.
        /// </summary>
        public static string lblAccountCreatedWithThisEmail {
            get {
                return ResourceManager.GetString("lblAccountCreatedWithThisEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem when creating your account?.
        /// </summary>
        public static string lblAccountCreationProblem {
            get {
                return ResourceManager.GetString("lblAccountCreationProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account will be locked by the system.
        /// </summary>
        public static string lblAccountLocked {
            get {
                return ResourceManager.GetString("lblAccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is not yet verified.
        /// </summary>
        public static string lblAccountNotVerified {
            get {
                return ResourceManager.GetString("lblAccountNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you new.
        /// </summary>
        public static string lblAreYourNew {
            get {
                return ResourceManager.GetString("lblAreYourNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ask to resend the activation e-mail.
        /// </summary>
        public static string lblAskForResendEmail {
            get {
                return ResourceManager.GetString("lblAskForResendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By creating an account.
        /// </summary>
        public static string lblByCreatingAccount {
            get {
                return ResourceManager.GetString("lblByCreatingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string lblChangePassword {
            get {
                return ResourceManager.GetString("lblChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your inbox.
        /// </summary>
        public static string lblCheckInbox {
            get {
                return ResourceManager.GetString("lblCheckInbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and check your address.
        /// </summary>
        public static string lblCheckYourAddress {
            get {
                return ResourceManager.GetString("lblCheckYourAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations.
        /// </summary>
        public static string lblCongratulations {
            get {
                return ResourceManager.GetString("lblCongratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string lblContactUs {
            get {
                return ResourceManager.GetString("lblContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you forget your password.
        /// </summary>
        public static string lblDidYouForgotYourPassword {
            get {
                return ResourceManager.GetString("lblDidYouForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does activation e-mail did not reach your inbox?.
        /// </summary>
        public static string lblEmailNoReachedMessage {
            get {
                return ResourceManager.GetString("lblEmailNoReachedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address was not found.
        /// </summary>
        public static string lblEmailNotFound {
            get {
                return ResourceManager.GetString("lblEmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail could not be sent to this address.
        /// </summary>
        public static string lblEmailNotSendToEmail {
            get {
                return ResourceManager.GetString("lblEmailNotSendToEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email and click on the activation link. E-mail, if they reach your address..
        /// </summary>
        public static string lblEmailSendingConfirmation {
            get {
                return ResourceManager.GetString("lblEmailSendingConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrance.
        /// </summary>
        public static string lblEntrance {
            get {
                return ResourceManager.GetString("lblEntrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The final step for your account.
        /// </summary>
        public static string lblFinalStepAccount {
            get {
                return ResourceManager.GetString("lblFinalStepAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string lblFirstName {
            get {
                return ResourceManager.GetString("lblFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password or can not access your account, even though you enter the correct password to do..
        /// </summary>
        public static string lblForgotPasswordMessage {
            get {
                return ResourceManager.GetString("lblForgotPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Refresh.
        /// </summary>
        public static string lblForgotRefresh {
            get {
                return ResourceManager.GetString("lblForgotRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a new activation e-mail.
        /// </summary>
        public static string lblGetNewActivationEmailMessage {
            get {
                return ResourceManager.GetString("lblGetNewActivationEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let us know.
        /// </summary>
        public static string lblLetUsKnow {
            get {
                return ResourceManager.GetString("lblLetUsKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string lblLogin {
            get {
                return ResourceManager.GetString("lblLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string lblNewPassword {
            get {
                return ResourceManager.GetString("lblNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a new password.
        /// </summary>
        public static string lblNewPasswordMessage {
            get {
                return ResourceManager.GetString("lblNewPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string lblOr {
            get {
                return ResourceManager.GetString("lblOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password invalid.
        /// </summary>
        public static string lblPasswordInvalid {
            get {
                return ResourceManager.GetString("lblPasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Reset.
        /// </summary>
        public static string lblPasswordReset {
            get {
                return ResourceManager.GetString("lblPasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem occurred while updating the password?.
        /// </summary>
        public static string lblPasswordUpdationProblem {
            get {
                return ResourceManager.GetString("lblPasswordUpdationProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please.
        /// </summary>
        public static string lblPlease {
            get {
                return ResourceManager.GetString("lblPlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is that a problem occurred while activating your account?.
        /// </summary>
        public static string lblProblemInActivationAccountMessage {
            get {
                return ResourceManager.GetString("lblProblemInActivationAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You agree to the contract. Despite the possibility of not boring, we recommend that you read this contract..
        /// </summary>
        public static string lblReadAgrementMessage {
            get {
                return ResourceManager.GetString("lblReadAgrementMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Now.
        /// </summary>
        public static string lblRegisterNow {
            get {
                return ResourceManager.GetString("lblRegisterNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string lblRememberMe {
            get {
                return ResourceManager.GetString("lblRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renew your password.
        /// </summary>
        public static string lblRenewYourPassword {
            get {
                return ResourceManager.GetString("lblRenewYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moments ago, we sent you an e-mail to reset your password..
        /// </summary>
        public static string lblResetPasswordConfirmMessage1 {
            get {
                return ResourceManager.GetString("lblResetPasswordConfirmMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email and password, click on the refresh link. E-mail, if they reach your address.
        /// </summary>
        public static string lblResetPasswordConfirmMessage2 {
            get {
                return ResourceManager.GetString("lblResetPasswordConfirmMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask again the password reset email.
        /// </summary>
        public static string lblResetPasswordConfirmMessage3 {
            get {
                return ResourceManager.GetString("lblResetPasswordConfirmMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string lblReturn {
            get {
                return ResourceManager.GetString("lblReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign up now.
        /// </summary>
        public static string lblSignUpNow {
            get {
                return ResourceManager.GetString("lblSignUpNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string lblSubmit {
            get {
                return ResourceManager.GetString("lblSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string lblSurname {
            get {
                return ResourceManager.GetString("lblSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of use.
        /// </summary>
        public static string lblTermsofUse {
            get {
                return ResourceManager.GetString("lblTermsofUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Log.
        /// </summary>
        public static string lblTheLog {
            get {
                return ResourceManager.GetString("lblTheLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This e-mail use.
        /// </summary>
        public static string lblThisEmailUsed {
            get {
                return ResourceManager.GetString("lblThisEmailUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have made too many attempts.
        /// </summary>
        public static string lblToManyAttemptsMessage {
            get {
                return ResourceManager.GetString("lblToManyAttemptsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again later.
        /// </summary>
        public static string lblTryAgainLaterMessage {
            get {
                return ResourceManager.GetString("lblTryAgainLaterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write and create a new password in your e-mail address.
        /// </summary>
        public static string lblWriteAndCreatePassword {
            get {
                return ResourceManager.GetString("lblWriteAndCreatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is verified before.
        /// </summary>
        public static string lblYourAccountVerifiedBefore {
            get {
                return ResourceManager.GetString("lblYourAccountVerifiedBefore", resourceCulture);
            }
        }
    }
}
