//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itsyazilim.Web.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ItsyazilimWebResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ItsyazilimWebResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Itsyazilim.Web.Domain.Resources.ItsyazilimWebResources", typeof(ItsyazilimWebResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Activation.
        /// </summary>
        public static string lblAccountActivation {
            get {
                return ResourceManager.GetString("lblAccountActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account created with this email.
        /// </summary>
        public static string lblAccountCreatedWithThisEmail {
            get {
                return ResourceManager.GetString("lblAccountCreatedWithThisEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem when creating your account?.
        /// </summary>
        public static string lblAccountCreationProblem {
            get {
                return ResourceManager.GetString("lblAccountCreationProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account will be locked by the system.
        /// </summary>
        public static string lblAccountLocked {
            get {
                return ResourceManager.GetString("lblAccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is not yet verified.
        /// </summary>
        public static string lblAccountNotVerified {
            get {
                return ResourceManager.GetString("lblAccountNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is verified before.
        /// </summary>
        public static string lblAccountVerifiedBefore {
            get {
                return ResourceManager.GetString("lblAccountVerifiedBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apple Store.
        /// </summary>
        public static string lblAppleStore {
            get {
                return ResourceManager.GetString("lblAppleStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you new.
        /// </summary>
        public static string lblAreYourNew {
            get {
                return ResourceManager.GetString("lblAreYourNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ask to resend the activation e-mail.
        /// </summary>
        public static string lblAskForResendEmail {
            get {
                return ResourceManager.GetString("lblAskForResendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benefits.
        /// </summary>
        public static string lblBenefits {
            get {
                return ResourceManager.GetString("lblBenefits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By creating an account.
        /// </summary>
        public static string lblByCreatingAccount {
            get {
                return ResourceManager.GetString("lblByCreatingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string lblChangePassword {
            get {
                return ResourceManager.GetString("lblChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your inbox.
        /// </summary>
        public static string lblCheckInbox {
            get {
                return ResourceManager.GetString("lblCheckInbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and check your address.
        /// </summary>
        public static string lblCheckYourAddress {
            get {
                return ResourceManager.GetString("lblCheckYourAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations.
        /// </summary>
        public static string lblCongratulations {
            get {
                return ResourceManager.GetString("lblCongratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string lblContactUs {
            get {
                return ResourceManager.GetString("lblContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to details.
        /// </summary>
        public static string lblDetails {
            get {
                return ResourceManager.GetString("lblDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you forget your password.
        /// </summary>
        public static string lblDidYouForgotYourPassword {
            get {
                return ResourceManager.GetString("lblDidYouForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please accounts in the e-mail and click on the activation link..
        /// </summary>
        public static string lblEmailAddressMessage1 {
            get {
                return ResourceManager.GetString("lblEmailAddressMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail, if they reach your address.
        /// </summary>
        public static string lblEmailAddressMessage2 {
            get {
                return ResourceManager.GetString("lblEmailAddressMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does activation e-mail did not reach your inbox?.
        /// </summary>
        public static string lblEmailNoReachedMessage {
            get {
                return ResourceManager.GetString("lblEmailNoReachedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address was not found.
        /// </summary>
        public static string lblEmailNotFound {
            get {
                return ResourceManager.GetString("lblEmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail could not be sent to this address.
        /// </summary>
        public static string lblEmailNotSendToEmail {
            get {
                return ResourceManager.GetString("lblEmailNotSendToEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email and click on the activation link. E-mail, if they reach your address..
        /// </summary>
        public static string lblEmailSendingConfirmation {
            get {
                return ResourceManager.GetString("lblEmailSendingConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrance.
        /// </summary>
        public static string lblEntrance {
            get {
                return ResourceManager.GetString("lblEntrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The final step for your account.
        /// </summary>
        public static string lblFinalStepAccount {
            get {
                return ResourceManager.GetString("lblFinalStepAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string lblFirstName {
            get {
                return ResourceManager.GetString("lblFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password or can not access your account, even though you enter the correct password to do..
        /// </summary>
        public static string lblForgotPasswordMessage {
            get {
                return ResourceManager.GetString("lblForgotPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Refresh.
        /// </summary>
        public static string lblForgotRefresh {
            get {
                return ResourceManager.GetString("lblForgotRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a new activation e-mail.
        /// </summary>
        public static string lblGetNewActivationEmailMessage {
            get {
                return ResourceManager.GetString("lblGetNewActivationEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Play.
        /// </summary>
        public static string lblGooglePlay {
            get {
                return ResourceManager.GetString("lblGooglePlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time to remember anything about logistics.
        /// </summary>
        public static string lblHomeMessage1 {
            get {
                return ResourceManager.GetString("lblHomeMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your business from anywhere.
        /// </summary>
        public static string lblHomeMessage10 {
            get {
                return ResourceManager.GetString("lblHomeMessage10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer layer bow of the bed, but the pain is always lot of football. But the price of the lot of laughter, it is not warm-sem easy anyone. In refinancing..
        /// </summary>
        public static string lblHomeMessage11 {
            get {
                return ResourceManager.GetString("lblHomeMessage11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To grow your logistics network monitoring your eyes.
        /// </summary>
        public static string lblHomeMessage12 {
            get {
                return ResourceManager.GetString("lblHomeMessage12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consectetuer adipiscing id lakes accu. Laoreet and before the ferry is not easy customization, and hate. Id, but Flash poisoned the skirt of the jaws. Unfortunately, at the gate of pregnant and lakes..
        /// </summary>
        public static string lblHomeMessage13 {
            get {
                return ResourceManager.GetString("lblHomeMessage13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart reports.
        /// </summary>
        public static string lblHomeMessage14 {
            get {
                return ResourceManager.GetString("lblHomeMessage14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increased performance.
        /// </summary>
        public static string lblHomeMessage15 {
            get {
                return ResourceManager.GetString("lblHomeMessage15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information on how to choose a time in the United States: for who is mourning malesuada. Will not be published In the notebook, but the pure sauce, chocolate sauce. Stress from gaming. Arrows and lakes is a highly professional long walk at times, who live in Arizona..
        /// </summary>
        public static string lblHomeMessage16 {
            get {
                return ResourceManager.GetString("lblHomeMessage16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why LTS TUBITAK.
        /// </summary>
        public static string lblHomeMessage17 {
            get {
                return ResourceManager.GetString("lblHomeMessage17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer layer bow of the bed, but the pain is always lot of football. But the price of the lot of laughter, it is not warm-sem easy anyone. In refinancing..
        /// </summary>
        public static string lblHomeMessage18 {
            get {
                return ResourceManager.GetString("lblHomeMessage18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What you should know.
        /// </summary>
        public static string lblHomeMessage19 {
            get {
                return ResourceManager.GetString("lblHomeMessage19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LTS TUBITAK throws a groundbreaking projects in the field of logistics with a new infrastructure.
        /// </summary>
        public static string lblHomeMessage2 {
            get {
                return ResourceManager.GetString("lblHomeMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consectetuer adipiscing id lakes accu. Laoreet and before the ferry is not easy customization, and hate. Id, but Flash poisoned the skirt of the jaws. Unfortunately, at the gate of pregnant and lakes..
        /// </summary>
        public static string lblHomeMessage20 {
            get {
                return ResourceManager.GetString("lblHomeMessage20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information on how to choose a time in the United States: for who is mourning malesuada. Will not be published In the notebook, but the pure sauce, chocolate sauce. Stress from gaming. Arrows and lakes is a highly professional long walk at times, who live in Arizona..
        /// </summary>
        public static string lblHomeMessage21 {
            get {
                return ResourceManager.GetString("lblHomeMessage21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your dream is our business.
        /// </summary>
        public static string lblHomeMessage22 {
            get {
                return ResourceManager.GetString("lblHomeMessage22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer layer bow of the bed, but the pain is always lot of football. But the price of the lot of laughter, it is not warm-sem easy anyone. In refinancing..
        /// </summary>
        public static string lblHomeMessage23 {
            get {
                return ResourceManager.GetString("lblHomeMessage23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud power at your fingertips.
        /// </summary>
        public static string lblHomeMessage3 {
            get {
                return ResourceManager.GetString("lblHomeMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer layer bow of the bed, but the pain is always lot of football. But the price of the lot of laughter, it is not warm-sem easy anyone. In refinancing..
        /// </summary>
        public static string lblHomeMessage4 {
            get {
                return ResourceManager.GetString("lblHomeMessage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the zamanda.
        /// </summary>
        public static string lblHomeMessage5 {
            get {
                return ResourceManager.GetString("lblHomeMessage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to many and great things.
        /// </summary>
        public static string lblHomeMessage6 {
            get {
                return ResourceManager.GetString("lblHomeMessage6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consectetuer adipiscing id lakes accu. Laoreet and before the ferry is not easy customization, and hate. Id, but Flash poisoned the skirt of the jaws. Unfortunately, at the gate of pregnant and lakes..
        /// </summary>
        public static string lblHomeMessage7 {
            get {
                return ResourceManager.GetString("lblHomeMessage7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power to your business with fast communication infrastructure.
        /// </summary>
        public static string lblHomeMessage8 {
            get {
                return ResourceManager.GetString("lblHomeMessage8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information on how to choose a time in the United States: for who is mourning malesuada. Will not be published In the notebook, but the pure sauce, chocolate sauce. Stress from gaming. Arrows and lakes is a highly professional long walk at times, who live in Arizona..
        /// </summary>
        public static string lblHomeMessage9 {
            get {
                return ResourceManager.GetString("lblHomeMessage9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation code is invalid.
        /// </summary>
        public static string lblInvalidActivationCode {
            get {
                return ResourceManager.GetString("lblInvalidActivationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let us know.
        /// </summary>
        public static string lblLetUsKnow {
            get {
                return ResourceManager.GetString("lblLetUsKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string lblLogin {
            get {
                return ResourceManager.GetString("lblLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LTS.
        /// </summary>
        public static string lblLTS {
            get {
                return ResourceManager.GetString("lblLTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string lblNewPassword {
            get {
                return ResourceManager.GetString("lblNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a new password.
        /// </summary>
        public static string lblNewPasswordMessage {
            get {
                return ResourceManager.GetString("lblNewPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string lblOr {
            get {
                return ResourceManager.GetString("lblOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password invalid.
        /// </summary>
        public static string lblPasswordInvalid {
            get {
                return ResourceManager.GetString("lblPasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Reset.
        /// </summary>
        public static string lblPasswordReset {
            get {
                return ResourceManager.GetString("lblPasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem occurred while updating the password?.
        /// </summary>
        public static string lblPasswordUpdationProblem {
            get {
                return ResourceManager.GetString("lblPasswordUpdationProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please.
        /// </summary>
        public static string lblPlease {
            get {
                return ResourceManager.GetString("lblPlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is that a problem occurred while activating your account?.
        /// </summary>
        public static string lblProblemInActivationAccountMessage {
            get {
                return ResourceManager.GetString("lblProblemInActivationAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You agree to the contract. Despite the possibility of not boring, we recommend that you read this contract..
        /// </summary>
        public static string lblReadAgrementMessage {
            get {
                return ResourceManager.GetString("lblReadAgrementMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Now.
        /// </summary>
        public static string lblRegisterNow {
            get {
                return ResourceManager.GetString("lblRegisterNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string lblRememberMe {
            get {
                return ResourceManager.GetString("lblRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renew your password.
        /// </summary>
        public static string lblRenewYourPassword {
            get {
                return ResourceManager.GetString("lblRenewYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moments ago, we sent you an e-mail to reset your password..
        /// </summary>
        public static string lblResetPasswordConfirmMessage1 {
            get {
                return ResourceManager.GetString("lblResetPasswordConfirmMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email and password, click on the refresh link. E-mail, if they reach your address.
        /// </summary>
        public static string lblResetPasswordConfirmMessage2 {
            get {
                return ResourceManager.GetString("lblResetPasswordConfirmMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask again the password reset email.
        /// </summary>
        public static string lblResetPasswordConfirmMessage3 {
            get {
                return ResourceManager.GetString("lblResetPasswordConfirmMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string lblReturn {
            get {
                return ResourceManager.GetString("lblReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign up now.
        /// </summary>
        public static string lblSignUpNow {
            get {
                return ResourceManager.GetString("lblSignUpNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string lblSubmit {
            get {
                return ResourceManager.GetString("lblSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string lblSurname {
            get {
                return ResourceManager.GetString("lblSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of use.
        /// </summary>
        public static string lblTermsofUse {
            get {
                return ResourceManager.GetString("lblTermsofUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Log.
        /// </summary>
        public static string lblTheLog {
            get {
                return ResourceManager.GetString("lblTheLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This e-mail use.
        /// </summary>
        public static string lblThisEmailUsed {
            get {
                return ResourceManager.GetString("lblThisEmailUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have made too many attempts.
        /// </summary>
        public static string lblToManyAttemptsMessage {
            get {
                return ResourceManager.GetString("lblToManyAttemptsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again later.
        /// </summary>
        public static string lblTryAgainLaterMessage {
            get {
                return ResourceManager.GetString("lblTryAgainLaterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TUBITAK.
        /// </summary>
        public static string lblTubitik {
            get {
                return ResourceManager.GetString("lblTubitik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Phone.
        /// </summary>
        public static string lblWindowsPhone {
            get {
                return ResourceManager.GetString("lblWindowsPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write and create a new password in your e-mail address.
        /// </summary>
        public static string lblWriteAndCreatePassword {
            get {
                return ResourceManager.GetString("lblWriteAndCreatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is verified before.
        /// </summary>
        public static string lblYourAccountVerifiedBefore {
            get {
                return ResourceManager.GetString("lblYourAccountVerifiedBefore", resourceCulture);
            }
        }
    }
}
