//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itsyazilim.Web.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ItsyazilimWebResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ItsyazilimWebResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Itsyazilim.Web.Domain.Resources.ItsyazilimWebResources", typeof(ItsyazilimWebResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account will be locked by the system.
        /// </summary>
        public static string lblAccountLocked {
            get {
                return ResourceManager.GetString("lblAccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is not yet verified.
        /// </summary>
        public static string lblAccountNotVerified {
            get {
                return ResourceManager.GetString("lblAccountNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you new.
        /// </summary>
        public static string lblAreYourNew {
            get {
                return ResourceManager.GetString("lblAreYourNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ask to resend the activation e-mail.
        /// </summary>
        public static string lblAskForResendEmail {
            get {
                return ResourceManager.GetString("lblAskForResendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string lblContactUs {
            get {
                return ResourceManager.GetString("lblContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address was not found.
        /// </summary>
        public static string lblEmailNotFound {
            get {
                return ResourceManager.GetString("lblEmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email and click on the activation link. E-mail, if they reach your address..
        /// </summary>
        public static string lblEmailSendingConfirmation {
            get {
                return ResourceManager.GetString("lblEmailSendingConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrance.
        /// </summary>
        public static string lblEntrance {
            get {
                return ResourceManager.GetString("lblEntrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password or can not access your account, even though you enter the correct password to do..
        /// </summary>
        public static string lblForgotPasswordMessage {
            get {
                return ResourceManager.GetString("lblForgotPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string lblLogin {
            get {
                return ResourceManager.GetString("lblLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password invalid.
        /// </summary>
        public static string lblPasswordInvalid {
            get {
                return ResourceManager.GetString("lblPasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please.
        /// </summary>
        public static string lblPlease {
            get {
                return ResourceManager.GetString("lblPlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string lblRememberMe {
            get {
                return ResourceManager.GetString("lblRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renew your password.
        /// </summary>
        public static string lblRenewYourPassword {
            get {
                return ResourceManager.GetString("lblRenewYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sign up now.
        /// </summary>
        public static string lblSignUpNow {
            get {
                return ResourceManager.GetString("lblSignUpNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have made too many attempts.
        /// </summary>
        public static string lblToManyAttemptsMessage {
            get {
                return ResourceManager.GetString("lblToManyAttemptsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again later.
        /// </summary>
        public static string lblTryAgainLaterMessage {
            get {
                return ResourceManager.GetString("lblTryAgainLaterMessage", resourceCulture);
            }
        }
    }
}
