//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itsyazilim.Web.Database.ORM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class LtsyazilimDatabaseEntities : DbContext
    {
        public LtsyazilimDatabaseEntities()
            : base("name=LtsyazilimDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C_OrderEndPositions> C_OrderEndPositions { get; set; }
        public DbSet<C_OrderStartPositions> C_OrderStartPositions { get; set; }
        public DbSet<DefLocationCity> DefLocationCities { get; set; }
        public DbSet<DefLocationCounty> DefLocationCounties { get; set; }
        public DbSet<DefLocationCountry> DefLocationCountries { get; set; }
        public DbSet<DefLocationRegion> DefLocationRegions { get; set; }
        public DbSet<DefOrderType> DefOrderTypes { get; set; }
        public DbSet<DefProductPackage> DefProductPackages { get; set; }
        public DbSet<DefProductProperty> DefProductProperties { get; set; }
        public DbSet<DefProductType> DefProductTypes { get; set; }
        public DbSet<DefProductUnit> DefProductUnits { get; set; }
        public DbSet<DefVehicleType> DefVehicleTypes { get; set; }
        public DbSet<Firm> Firms { get; set; }
        public DbSet<LogMembershipCheckPasswordRenewalCode> LogMembershipCheckPasswordRenewalCodes { get; set; }
        public DbSet<LogMembershipLogin> LogMembershipLogins { get; set; }
        public DbSet<LogMembershipRegisterCheckCode> LogMembershipRegisterCheckCodes { get; set; }
        public DbSet<LogMembershipRegisterReSendCode> LogMembershipRegisterReSendCodes { get; set; }
        public DbSet<LogMembershipSendPasswordRenewalCode> LogMembershipSendPasswordRenewalCodes { get; set; }
        public DbSet<LogSystemMailSend> LogSystemMailSends { get; set; }
        public DbSet<MapFirmToUser> MapFirmToUsers { get; set; }
        public DbSet<Membership> Memberships { get; set; }
        public DbSet<MembershipPasswordRenewal> MembershipPasswordRenewals { get; set; }
        public DbSet<OrderDetail> OrderDetails { get; set; }
        public DbSet<OrderProductProperty> OrderProductProperties { get; set; }
        public DbSet<OrderRoute> OrderRoutes { get; set; }
        public DbSet<Order> Orders { get; set; }
    
    }
}
