//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itsyazilim.Web.Database.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        public Module()
        {
            this.ModuleRoleMappings = new HashSet<ModuleRoleMapping>();
        }
    
        public int ModuleId { get; set; }
        public string ModuleName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<ModuleRoleMapping> ModuleRoleMappings { get; set; }
    }
}
