//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Itsyazilim.Web.Database.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderProductProperty
    {
        public long OrderProductPropertiesId { get; set; }
        public Nullable<long> OrderDetailId { get; set; }
        public Nullable<short> ProductPropertyId { get; set; }
    }
}
