//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-01-28 - 12:02:30
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Itsyazilim.Web.Domain;
using Itsyazilim.Web.Database.ORM;

namespace Itsyazilim.Web.Domain
{

    /// <summary>
    /// Assembler for <see cref="C_OrderEndPositions"/> and <see cref="C_OrderEndPositionsDTO"/>.
    /// </summary>
    public static partial class C_OrderEndPositionsAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="C_OrderEndPositionsDTO"/> converted from <see cref="C_OrderEndPositions"/>.</param>
        static partial void OnDTO(this C_OrderEndPositions entity, C_OrderEndPositionsDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="C_OrderEndPositions"/> converted from <see cref="C_OrderEndPositionsDTO"/>.</param>
        static partial void OnEntity(this C_OrderEndPositionsDTO dto, C_OrderEndPositions entity);

        /// <summary>
        /// Converts this instance of <see cref="C_OrderEndPositionsDTO"/> to an instance of <see cref="C_OrderEndPositions"/>.
        /// </summary>
        /// <param name="dto"><see cref="C_OrderEndPositionsDTO"/> to convert.</param>
        public static C_OrderEndPositions ToEntity(this C_OrderEndPositionsDTO dto)
        {
            if (dto == null) return null;

            var entity = new C_OrderEndPositions();

            entity.OrderEndPositionId = dto.OrderEndPositionId;
            entity.OrderId = dto.OrderId;
            entity.CountyId = dto.CountyId;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="C_OrderEndPositions"/> to an instance of <see cref="C_OrderEndPositionsDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="C_OrderEndPositions"/> to convert.</param>
        public static C_OrderEndPositionsDTO ToDTO(this C_OrderEndPositions entity)
        {
            if (entity == null) return null;

            var dto = new C_OrderEndPositionsDTO();

            dto.OrderEndPositionId = entity.OrderEndPositionId;
            dto.OrderId = entity.OrderId;
            dto.CountyId = entity.CountyId;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="C_OrderEndPositionsDTO"/> to an instance of <see cref="C_OrderEndPositions"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<C_OrderEndPositions> ToEntities(this IEnumerable<C_OrderEndPositionsDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="C_OrderEndPositions"/> to an instance of <see cref="C_OrderEndPositionsDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<C_OrderEndPositionsDTO> ToDTOs(this IEnumerable<C_OrderEndPositions> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
