//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-01-28 - 12:02:30
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Itsyazilim.Web.Domain;
using Itsyazilim.Web.Database.ORM;

namespace Itsyazilim.Web.Domain
{

    /// <summary>
    /// Assembler for <see cref="DefLocationCity"/> and <see cref="DefLocationCityDTO"/>.
    /// </summary>
    public static partial class DefLocationCityAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="DefLocationCityDTO"/> converted from <see cref="DefLocationCity"/>.</param>
        static partial void OnDTO(this DefLocationCity entity, DefLocationCityDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="DefLocationCity"/> converted from <see cref="DefLocationCityDTO"/>.</param>
        static partial void OnEntity(this DefLocationCityDTO dto, DefLocationCity entity);

        /// <summary>
        /// Converts this instance of <see cref="DefLocationCityDTO"/> to an instance of <see cref="DefLocationCity"/>.
        /// </summary>
        /// <param name="dto"><see cref="DefLocationCityDTO"/> to convert.</param>
        public static DefLocationCity ToEntity(this DefLocationCityDTO dto)
        {
            if (dto == null) return null;

            var entity = new DefLocationCity();

            entity.CityId = dto.CityId;
            entity.Name = dto.Name;
            entity.CountryId = dto.CountryId;
            entity.LocalCode = dto.LocalCode;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="DefLocationCity"/> to an instance of <see cref="DefLocationCityDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="DefLocationCity"/> to convert.</param>
        public static DefLocationCityDTO ToDTO(this DefLocationCity entity)
        {
            if (entity == null) return null;

            var dto = new DefLocationCityDTO();

            dto.CityId = entity.CityId;
            dto.Name = entity.Name;
            dto.CountryId = entity.CountryId;
            dto.LocalCode = entity.LocalCode;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="DefLocationCityDTO"/> to an instance of <see cref="DefLocationCity"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<DefLocationCity> ToEntities(this IEnumerable<DefLocationCityDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="DefLocationCity"/> to an instance of <see cref="DefLocationCityDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<DefLocationCityDTO> ToDTOs(this IEnumerable<DefLocationCity> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
