//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-01-28 - 12:02:30
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Itsyazilim.Web.Domain;
using Itsyazilim.Web.Database.ORM;

namespace Itsyazilim.Web.Domain
{

    /// <summary>
    /// Assembler for <see cref="DefLocationCounty"/> and <see cref="DefLocationCountyDTO"/>.
    /// </summary>
    public static partial class DefLocationCountyAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="DefLocationCountyDTO"/> converted from <see cref="DefLocationCounty"/>.</param>
        static partial void OnDTO(this DefLocationCounty entity, DefLocationCountyDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="DefLocationCounty"/> converted from <see cref="DefLocationCountyDTO"/>.</param>
        static partial void OnEntity(this DefLocationCountyDTO dto, DefLocationCounty entity);

        /// <summary>
        /// Converts this instance of <see cref="DefLocationCountyDTO"/> to an instance of <see cref="DefLocationCounty"/>.
        /// </summary>
        /// <param name="dto"><see cref="DefLocationCountyDTO"/> to convert.</param>
        public static DefLocationCounty ToEntity(this DefLocationCountyDTO dto)
        {
            if (dto == null) return null;

            var entity = new DefLocationCounty();

            entity.CountyId = dto.CountyId;
            entity.Name = dto.Name;
            entity.CityId = dto.CityId;
            entity.LocalCode = dto.LocalCode;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="DefLocationCounty"/> to an instance of <see cref="DefLocationCountyDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="DefLocationCounty"/> to convert.</param>
        public static DefLocationCountyDTO ToDTO(this DefLocationCounty entity)
        {
            if (entity == null) return null;

            var dto = new DefLocationCountyDTO();

            dto.CountyId = entity.CountyId;
            dto.Name = entity.Name;
            dto.CityId = entity.CityId;
            dto.LocalCode = entity.LocalCode;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="DefLocationCountyDTO"/> to an instance of <see cref="DefLocationCounty"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<DefLocationCounty> ToEntities(this IEnumerable<DefLocationCountyDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="DefLocationCounty"/> to an instance of <see cref="DefLocationCountyDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<DefLocationCountyDTO> ToDTOs(this IEnumerable<DefLocationCounty> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
