//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-01-28 - 12:02:30
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Itsyazilim.Web.Domain;
using Itsyazilim.Web.Database.ORM;

namespace Itsyazilim.Web.Domain.Assemblers
{

    /// <summary>
    /// Assembler for <see cref="DefLocationCountry"/> and <see cref="DefLocationCountryDTO"/>.
    /// </summary>
    public static partial class DefLocationCountryAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="DefLocationCountryDTO"/> converted from <see cref="DefLocationCountry"/>.</param>
        static partial void OnDTO(this DefLocationCountry entity, DefLocationCountryDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="DefLocationCountry"/> converted from <see cref="DefLocationCountryDTO"/>.</param>
        static partial void OnEntity(this DefLocationCountryDTO dto, DefLocationCountry entity);

        /// <summary>
        /// Converts this instance of <see cref="DefLocationCountryDTO"/> to an instance of <see cref="DefLocationCountry"/>.
        /// </summary>
        /// <param name="dto"><see cref="DefLocationCountryDTO"/> to convert.</param>
        public static DefLocationCountry ToEntity(this DefLocationCountryDTO dto)
        {
            if (dto == null) return null;

            var entity = new DefLocationCountry();

            entity.CountryId = dto.CountryId;
            entity.Name = dto.Name;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="DefLocationCountry"/> to an instance of <see cref="DefLocationCountryDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="DefLocationCountry"/> to convert.</param>
        public static DefLocationCountryDTO ToDTO(this DefLocationCountry entity)
        {
            if (entity == null) return null;

            var dto = new DefLocationCountryDTO();

            dto.CountryId = entity.CountryId;
            dto.Name = entity.Name;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="DefLocationCountryDTO"/> to an instance of <see cref="DefLocationCountry"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<DefLocationCountry> ToEntities(this IEnumerable<DefLocationCountryDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="DefLocationCountry"/> to an instance of <see cref="DefLocationCountryDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<DefLocationCountryDTO> ToDTOs(this IEnumerable<DefLocationCountry> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
