//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-01-28 - 12:02:31
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Itsyazilim.Web.Domain;
using Itsyazilim.Web.Database.ORM;

namespace Itsyazilim.Web.Domain
{

    /// <summary>
    /// Assembler for <see cref="DefProductProperty"/> and <see cref="DefProductPropertyDTO"/>.
    /// </summary>
    public static partial class DefProductPropertyAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="DefProductPropertyDTO"/> converted from <see cref="DefProductProperty"/>.</param>
        static partial void OnDTO(this DefProductProperty entity, DefProductPropertyDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="DefProductProperty"/> converted from <see cref="DefProductPropertyDTO"/>.</param>
        static partial void OnEntity(this DefProductPropertyDTO dto, DefProductProperty entity);

        /// <summary>
        /// Converts this instance of <see cref="DefProductPropertyDTO"/> to an instance of <see cref="DefProductProperty"/>.
        /// </summary>
        /// <param name="dto"><see cref="DefProductPropertyDTO"/> to convert.</param>
        public static DefProductProperty ToEntity(this DefProductPropertyDTO dto)
        {
            if (dto == null) return null;

            var entity = new DefProductProperty();

            entity.ProductPropertyId = dto.ProductPropertyId;
            entity.ProductPropertyName = dto.ProductPropertyName;
            entity.CreatedBy = dto.CreatedBy;
            entity.CreatedOn = dto.CreatedOn;
            entity.IsDeleted = dto.IsDeleted;
            entity.DeletedBy = dto.DeletedBy;
            entity.DeletedOn = dto.DeletedOn;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="DefProductProperty"/> to an instance of <see cref="DefProductPropertyDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="DefProductProperty"/> to convert.</param>
        public static DefProductPropertyDTO ToDTO(this DefProductProperty entity)
        {
            if (entity == null) return null;

            var dto = new DefProductPropertyDTO();

            dto.ProductPropertyId = entity.ProductPropertyId;
            dto.ProductPropertyName = entity.ProductPropertyName;
            dto.CreatedBy = entity.CreatedBy;
            dto.CreatedOn = entity.CreatedOn;
            dto.IsDeleted = entity.IsDeleted;
            dto.DeletedBy = entity.DeletedBy;
            dto.DeletedOn = entity.DeletedOn;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="DefProductPropertyDTO"/> to an instance of <see cref="DefProductProperty"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<DefProductProperty> ToEntities(this IEnumerable<DefProductPropertyDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="DefProductProperty"/> to an instance of <see cref="DefProductPropertyDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<DefProductPropertyDTO> ToDTOs(this IEnumerable<DefProductProperty> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
