//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-01-28 - 12:02:31
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Itsyazilim.Web.Domain;
using Itsyazilim.Web.Database.ORM;

namespace Itsyazilim.Web.Domain
{

    /// <summary>
    /// Assembler for <see cref="DefProductUnit"/> and <see cref="DefProductUnitDTO"/>.
    /// </summary>
    public static partial class DefProductUnitAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="DefProductUnitDTO"/> converted from <see cref="DefProductUnit"/>.</param>
        static partial void OnDTO(this DefProductUnit entity, DefProductUnitDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="DefProductUnit"/> converted from <see cref="DefProductUnitDTO"/>.</param>
        static partial void OnEntity(this DefProductUnitDTO dto, DefProductUnit entity);

        /// <summary>
        /// Converts this instance of <see cref="DefProductUnitDTO"/> to an instance of <see cref="DefProductUnit"/>.
        /// </summary>
        /// <param name="dto"><see cref="DefProductUnitDTO"/> to convert.</param>
        public static DefProductUnit ToEntity(this DefProductUnitDTO dto)
        {
            if (dto == null) return null;

            var entity = new DefProductUnit();

            entity.ProductUnitId = dto.ProductUnitId;
            entity.ProductUnitName = dto.ProductUnitName;
            entity.CreatedBy = dto.CreatedBy;
            entity.CreatedOn = dto.CreatedOn;
            entity.IsDeleted = dto.IsDeleted;
            entity.DeletedBy = dto.DeletedBy;
            entity.DeletedOn = dto.DeletedOn;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="DefProductUnit"/> to an instance of <see cref="DefProductUnitDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="DefProductUnit"/> to convert.</param>
        public static DefProductUnitDTO ToDTO(this DefProductUnit entity)
        {
            if (entity == null) return null;

            var dto = new DefProductUnitDTO();

            dto.ProductUnitId = entity.ProductUnitId;
            dto.ProductUnitName = entity.ProductUnitName;
            dto.CreatedBy = entity.CreatedBy;
            dto.CreatedOn = entity.CreatedOn;
            dto.IsDeleted = entity.IsDeleted;
            dto.DeletedBy = entity.DeletedBy;
            dto.DeletedOn = entity.DeletedOn;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="DefProductUnitDTO"/> to an instance of <see cref="DefProductUnit"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<DefProductUnit> ToEntities(this IEnumerable<DefProductUnitDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="DefProductUnit"/> to an instance of <see cref="DefProductUnitDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<DefProductUnitDTO> ToDTOs(this IEnumerable<DefProductUnit> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
