//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-01-28 - 12:02:31
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Itsyazilim.Web.Domain;
using Itsyazilim.Web.Database.ORM;

namespace Itsyazilim.Web.Domain.Assemblers
{

    /// <summary>
    /// Assembler for <see cref="Firm"/> and <see cref="FirmDTO"/>.
    /// </summary>
    public static partial class FirmAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="FirmDTO"/> converted from <see cref="Firm"/>.</param>
        static partial void OnDTO(this Firm entity, FirmDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="Firm"/> converted from <see cref="FirmDTO"/>.</param>
        static partial void OnEntity(this FirmDTO dto, Firm entity);

        /// <summary>
        /// Converts this instance of <see cref="FirmDTO"/> to an instance of <see cref="Firm"/>.
        /// </summary>
        /// <param name="dto"><see cref="FirmDTO"/> to convert.</param>
        public static Firm ToEntity(this FirmDTO dto)
        {
            if (dto == null) return null;

            var entity = new Firm();

            entity.FirmId = dto.FirmId;
            entity.FirmName = dto.FirmName;
            entity.CountyId = dto.CountyId;
            entity.Address = dto.Address;
            entity.Phone1 = dto.Phone1;
            entity.Phone2 = dto.Phone2;
            entity.Fax = dto.Fax;
            entity.MobilePhone = dto.MobilePhone;
            entity.Email = dto.Email;
            entity.WebSite = dto.WebSite;
            entity.TaxOffice = dto.TaxOffice;
            entity.TaxNo = dto.TaxNo;
            entity.CreatedBy = dto.CreatedBy;
            entity.IsApproved = dto.IsApproved;
            entity.ApprovedBy = dto.ApprovedBy;
            entity.ApprovedOn = dto.ApprovedOn;
            entity.CreatedOn = dto.CreatedOn;
            entity.UpdatedOn = dto.UpdatedOn;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="Firm"/> to an instance of <see cref="FirmDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="Firm"/> to convert.</param>
        public static FirmDTO ToDTO(this Firm entity)
        {
            if (entity == null) return null;

            var dto = new FirmDTO();

            dto.FirmId = entity.FirmId;
            dto.FirmName = entity.FirmName;
            dto.CountyId = entity.CountyId;
            dto.Address = entity.Address;
            dto.Phone1 = entity.Phone1;
            dto.Phone2 = entity.Phone2;
            dto.Fax = entity.Fax;
            dto.MobilePhone = entity.MobilePhone;
            dto.Email = entity.Email;
            dto.WebSite = entity.WebSite;
            dto.TaxOffice = entity.TaxOffice;
            dto.TaxNo = entity.TaxNo;
            dto.CreatedBy = entity.CreatedBy;
            dto.IsApproved = entity.IsApproved;
            dto.ApprovedBy = entity.ApprovedBy;
            dto.ApprovedOn = entity.ApprovedOn;
            dto.CreatedOn = entity.CreatedOn;
            dto.UpdatedOn = entity.UpdatedOn;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="FirmDTO"/> to an instance of <see cref="Firm"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<Firm> ToEntities(this IEnumerable<FirmDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="Firm"/> to an instance of <see cref="FirmDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<FirmDTO> ToDTOs(this IEnumerable<Firm> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
