//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-01-28 - 12:02:32
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Itsyazilim.Web.Domain;
using Itsyazilim.Web.Database.ORM;

namespace Itsyazilim.Web.Domain.Assemblers
{

    /// <summary>
    /// Assembler for <see cref="LogMembershipRegisterCheckCode"/> and <see cref="LogMembershipRegisterCheckCodeDTO"/>.
    /// </summary>
    public static partial class LogMembershipRegisterCheckCodeAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="LogMembershipRegisterCheckCodeDTO"/> converted from <see cref="LogMembershipRegisterCheckCode"/>.</param>
        static partial void OnDTO(this LogMembershipRegisterCheckCode entity, LogMembershipRegisterCheckCodeDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="LogMembershipRegisterCheckCode"/> converted from <see cref="LogMembershipRegisterCheckCodeDTO"/>.</param>
        static partial void OnEntity(this LogMembershipRegisterCheckCodeDTO dto, LogMembershipRegisterCheckCode entity);

        /// <summary>
        /// Converts this instance of <see cref="LogMembershipRegisterCheckCodeDTO"/> to an instance of <see cref="LogMembershipRegisterCheckCode"/>.
        /// </summary>
        /// <param name="dto"><see cref="LogMembershipRegisterCheckCodeDTO"/> to convert.</param>
        public static LogMembershipRegisterCheckCode ToEntity(this LogMembershipRegisterCheckCodeDTO dto)
        {
            if (dto == null) return null;

            var entity = new LogMembershipRegisterCheckCode();

            entity.LogId = dto.LogId;
            entity.Email = dto.Email;
            entity.Result = dto.Result;
            entity.IP = dto.IP;
            entity.CreatedOn = dto.CreatedOn;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="LogMembershipRegisterCheckCode"/> to an instance of <see cref="LogMembershipRegisterCheckCodeDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="LogMembershipRegisterCheckCode"/> to convert.</param>
        public static LogMembershipRegisterCheckCodeDTO ToDTO(this LogMembershipRegisterCheckCode entity)
        {
            if (entity == null) return null;

            var dto = new LogMembershipRegisterCheckCodeDTO();

            dto.LogId = entity.LogId;
            dto.Email = entity.Email;
            dto.Result = entity.Result;
            dto.IP = entity.IP;
            dto.CreatedOn = entity.CreatedOn;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="LogMembershipRegisterCheckCodeDTO"/> to an instance of <see cref="LogMembershipRegisterCheckCode"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<LogMembershipRegisterCheckCode> ToEntities(this IEnumerable<LogMembershipRegisterCheckCodeDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="LogMembershipRegisterCheckCode"/> to an instance of <see cref="LogMembershipRegisterCheckCodeDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<LogMembershipRegisterCheckCodeDTO> ToDTOs(this IEnumerable<LogMembershipRegisterCheckCode> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
