//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-01-28 - 12:02:31
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Itsyazilim.Web.Domain;
using Itsyazilim.Web.Database.ORM;

namespace Itsyazilim.Web.Domain.Assemblers
{

    /// <summary>
    /// Assembler for <see cref="LogMembershipLogin"/> and <see cref="LogMembershipLoginDTO"/>.
    /// </summary>
    public static partial class LogMembershipLoginAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="LogMembershipLoginDTO"/> converted from <see cref="LogMembershipLogin"/>.</param>
        static partial void OnDTO(this LogMembershipLogin entity, LogMembershipLoginDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="LogMembershipLogin"/> converted from <see cref="LogMembershipLoginDTO"/>.</param>
        static partial void OnEntity(this LogMembershipLoginDTO dto, LogMembershipLogin entity);

        /// <summary>
        /// Converts this instance of <see cref="LogMembershipLoginDTO"/> to an instance of <see cref="LogMembershipLogin"/>.
        /// </summary>
        /// <param name="dto"><see cref="LogMembershipLoginDTO"/> to convert.</param>
        public static LogMembershipLogin ToEntity(this LogMembershipLoginDTO dto)
        {
            if (dto == null) return null;

            var entity = new LogMembershipLogin();

            entity.LogId = dto.LogId;
            entity.Email = dto.Email;
            entity.Result = dto.Result;
            entity.IP = dto.IP;
            entity.CreatedOn = dto.CreatedOn;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="LogMembershipLogin"/> to an instance of <see cref="LogMembershipLoginDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="LogMembershipLogin"/> to convert.</param>
        public static LogMembershipLoginDTO ToDTO(this LogMembershipLogin entity)
        {
            if (entity == null) return null;

            var dto = new LogMembershipLoginDTO();

            dto.LogId = entity.LogId;
            dto.Email = entity.Email;
            dto.Result = entity.Result;
            dto.IP = entity.IP;
            dto.CreatedOn = entity.CreatedOn;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="LogMembershipLoginDTO"/> to an instance of <see cref="LogMembershipLogin"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<LogMembershipLogin> ToEntities(this IEnumerable<LogMembershipLoginDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="LogMembershipLogin"/> to an instance of <see cref="LogMembershipLoginDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<LogMembershipLoginDTO> ToDTOs(this IEnumerable<LogMembershipLogin> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
