//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015-01-28 - 12:02:32
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Itsyazilim.Web.Domain;
using Itsyazilim.Web.Database.ORM;

namespace Itsyazilim.Web.Domain
{

    /// <summary>
    /// Assembler for <see cref="LogMembershipRegisterReSendCode"/> and <see cref="LogMembershipRegisterReSendCodeDTO"/>.
    /// </summary>
    public static partial class LogMembershipRegisterReSendCodeAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="LogMembershipRegisterReSendCodeDTO"/> converted from <see cref="LogMembershipRegisterReSendCode"/>.</param>
        static partial void OnDTO(this LogMembershipRegisterReSendCode entity, LogMembershipRegisterReSendCodeDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="LogMembershipRegisterReSendCode"/> converted from <see cref="LogMembershipRegisterReSendCodeDTO"/>.</param>
        static partial void OnEntity(this LogMembershipRegisterReSendCodeDTO dto, LogMembershipRegisterReSendCode entity);

        /// <summary>
        /// Converts this instance of <see cref="LogMembershipRegisterReSendCodeDTO"/> to an instance of <see cref="LogMembershipRegisterReSendCode"/>.
        /// </summary>
        /// <param name="dto"><see cref="LogMembershipRegisterReSendCodeDTO"/> to convert.</param>
        public static LogMembershipRegisterReSendCode ToEntity(this LogMembershipRegisterReSendCodeDTO dto)
        {
            if (dto == null) return null;

            var entity = new LogMembershipRegisterReSendCode();

            entity.LogId = dto.LogId;
            entity.Email = dto.Email;
            entity.Result = dto.Result;
            entity.IP = dto.IP;
            entity.CreatedOn = dto.CreatedOn;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="LogMembershipRegisterReSendCode"/> to an instance of <see cref="LogMembershipRegisterReSendCodeDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="LogMembershipRegisterReSendCode"/> to convert.</param>
        public static LogMembershipRegisterReSendCodeDTO ToDTO(this LogMembershipRegisterReSendCode entity)
        {
            if (entity == null) return null;

            var dto = new LogMembershipRegisterReSendCodeDTO();

            dto.LogId = entity.LogId;
            dto.Email = entity.Email;
            dto.Result = entity.Result;
            dto.IP = entity.IP;
            dto.CreatedOn = entity.CreatedOn;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="LogMembershipRegisterReSendCodeDTO"/> to an instance of <see cref="LogMembershipRegisterReSendCode"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<LogMembershipRegisterReSendCode> ToEntities(this IEnumerable<LogMembershipRegisterReSendCodeDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="LogMembershipRegisterReSendCode"/> to an instance of <see cref="LogMembershipRegisterReSendCodeDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<LogMembershipRegisterReSendCodeDTO> ToDTOs(this IEnumerable<LogMembershipRegisterReSendCode> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
