//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/02/03 - 22:39:28
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Itsyazilim.Web.Domain;
using Itsyazilim.Web.Database.ORM;


namespace Itsyazilim.Web.Domain
{

    /// <summary>
    /// Assembler for <see cref="MemberRoleMapping"/> and <see cref="MemberRoleMappingDTO"/>.
    /// </summary>
    public static partial class MemberRoleMappingAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="MemberRoleMappingDTO"/> converted from <see cref="MemberRoleMapping"/>.</param>
        static partial void OnDTO(this MemberRoleMapping entity, MemberRoleMappingDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="MemberRoleMapping"/> converted from <see cref="MemberRoleMappingDTO"/>.</param>
        static partial void OnEntity(this MemberRoleMappingDTO dto, MemberRoleMapping entity);

        /// <summary>
        /// Converts this instance of <see cref="MemberRoleMappingDTO"/> to an instance of <see cref="MemberRoleMapping"/>.
        /// </summary>
        /// <param name="dto"><see cref="MemberRoleMappingDTO"/> to convert.</param>
        public static MemberRoleMapping ToEntity(this MemberRoleMappingDTO dto)
        {
            if (dto == null) return null;

            var entity = new MemberRoleMapping();

            entity.RoleMappingId = dto.RoleMappingId;
            entity.RoleId = dto.RoleId;
            entity.MemberId = dto.MemberId;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="MemberRoleMapping"/> to an instance of <see cref="MemberRoleMappingDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="MemberRoleMapping"/> to convert.</param>
        public static MemberRoleMappingDTO ToDTO(this MemberRoleMapping entity)
        {
            if (entity == null) return null;

            var dto = new MemberRoleMappingDTO();

            dto.RoleMappingId = entity.RoleMappingId;
            dto.RoleId = entity.RoleId;
            dto.MemberId = entity.MemberId;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="MemberRoleMappingDTO"/> to an instance of <see cref="MemberRoleMapping"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<MemberRoleMapping> ToEntities(this IEnumerable<MemberRoleMappingDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="MemberRoleMapping"/> to an instance of <see cref="MemberRoleMappingDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<MemberRoleMappingDTO> ToDTOs(this IEnumerable<MemberRoleMapping> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
