//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/02/03 - 22:39:28
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Itsyazilim.Web.Domain;
using Itsyazilim.Web.Database.ORM;


namespace Itsyazilim.Web.Domain
{

    /// <summary>
    /// Assembler for <see cref="MemeberRoleMapping"/> and <see cref="MemeberRoleMappingDTO"/>.
    /// </summary>
    public static partial class MemeberRoleMappingAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="MemeberRoleMappingDTO"/> converted from <see cref="MemeberRoleMapping"/>.</param>
        static partial void OnDTO(this MemeberRoleMapping entity, MemeberRoleMappingDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="MemeberRoleMapping"/> converted from <see cref="MemeberRoleMappingDTO"/>.</param>
        static partial void OnEntity(this MemeberRoleMappingDTO dto, MemeberRoleMapping entity);

        /// <summary>
        /// Converts this instance of <see cref="MemeberRoleMappingDTO"/> to an instance of <see cref="MemeberRoleMapping"/>.
        /// </summary>
        /// <param name="dto"><see cref="MemeberRoleMappingDTO"/> to convert.</param>
        public static MemeberRoleMapping ToEntity(this MemeberRoleMappingDTO dto)
        {
            if (dto == null) return null;

            var entity = new MemeberRoleMapping();

            entity.RoleMappingId = dto.RoleMappingId;
            entity.RoleId = dto.RoleId;
            entity.UserId = dto.UserId;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="MemeberRoleMapping"/> to an instance of <see cref="MemeberRoleMappingDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="MemeberRoleMapping"/> to convert.</param>
        public static MemeberRoleMappingDTO ToDTO(this MemeberRoleMapping entity)
        {
            if (entity == null) return null;

            var dto = new MemeberRoleMappingDTO();

            dto.RoleMappingId = entity.RoleMappingId;
            dto.RoleId = entity.RoleId;
            dto.UserId = entity.UserId;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="MemeberRoleMappingDTO"/> to an instance of <see cref="MemeberRoleMapping"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<MemeberRoleMapping> ToEntities(this IEnumerable<MemeberRoleMappingDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="MemeberRoleMapping"/> to an instance of <see cref="MemeberRoleMappingDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<MemeberRoleMappingDTO> ToDTOs(this IEnumerable<MemeberRoleMapping> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
