//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/02/03 - 22:39:28
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Itsyazilim.Web.Domain;
using Itsyazilim.Web.Database.ORM;


namespace Itsyazilim.Web.Domain
{

    /// <summary>
    /// Assembler for <see cref="ModuleRoleMapping"/> and <see cref="ModuleRoleMappingDTO"/>.
    /// </summary>
    public static partial class ModuleRoleMappingAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="ModuleRoleMappingDTO"/> converted from <see cref="ModuleRoleMapping"/>.</param>
        static partial void OnDTO(this ModuleRoleMapping entity, ModuleRoleMappingDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="ModuleRoleMapping"/> converted from <see cref="ModuleRoleMappingDTO"/>.</param>
        static partial void OnEntity(this ModuleRoleMappingDTO dto, ModuleRoleMapping entity);

        /// <summary>
        /// Converts this instance of <see cref="ModuleRoleMappingDTO"/> to an instance of <see cref="ModuleRoleMapping"/>.
        /// </summary>
        /// <param name="dto"><see cref="ModuleRoleMappingDTO"/> to convert.</param>
        public static ModuleRoleMapping ToEntity(this ModuleRoleMappingDTO dto)
        {
            if (dto == null) return null;

            var entity = new ModuleRoleMapping();

            entity.ModuleRoleMappingId = dto.ModuleRoleMappingId;
            entity.RoleId = dto.RoleId;
            entity.ModuleId = dto.ModuleId;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="ModuleRoleMapping"/> to an instance of <see cref="ModuleRoleMappingDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="ModuleRoleMapping"/> to convert.</param>
        public static ModuleRoleMappingDTO ToDTO(this ModuleRoleMapping entity)
        {
            if (entity == null) return null;

            var dto = new ModuleRoleMappingDTO();

            dto.ModuleRoleMappingId = entity.ModuleRoleMappingId;
            dto.RoleId = entity.RoleId;
            dto.ModuleId = entity.ModuleId;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="ModuleRoleMappingDTO"/> to an instance of <see cref="ModuleRoleMapping"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<ModuleRoleMapping> ToEntities(this IEnumerable<ModuleRoleMappingDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="ModuleRoleMapping"/> to an instance of <see cref="ModuleRoleMappingDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<ModuleRoleMappingDTO> ToDTOs(this IEnumerable<ModuleRoleMapping> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
