//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/02/03 - 22:39:28
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Itsyazilim.Web.Domain;
using Itsyazilim.Web.Database.ORM;


namespace Itsyazilim.Web.Domain
{

    /// <summary>
    /// Assembler for <see cref="Module"/> and <see cref="ModuleDTO"/>.
    /// </summary>
    public static partial class ModuleAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="ModuleDTO"/> converted from <see cref="Module"/>.</param>
        static partial void OnDTO(this Module entity, ModuleDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="Module"/> converted from <see cref="ModuleDTO"/>.</param>
        static partial void OnEntity(this ModuleDTO dto, Module entity);

        /// <summary>
        /// Converts this instance of <see cref="ModuleDTO"/> to an instance of <see cref="Module"/>.
        /// </summary>
        /// <param name="dto"><see cref="ModuleDTO"/> to convert.</param>
        public static Module ToEntity(this ModuleDTO dto)
        {
            if (dto == null) return null;

            var entity = new Module();

            entity.ModuleId = dto.ModuleId;
            entity.ModuleName = dto.ModuleName;
            entity.Description = dto.Description;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="Module"/> to an instance of <see cref="ModuleDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="Module"/> to convert.</param>
        public static ModuleDTO ToDTO(this Module entity)
        {
            if (entity == null) return null;

            var dto = new ModuleDTO();

            dto.ModuleId = entity.ModuleId;
            dto.ModuleName = entity.ModuleName;
            dto.Description = entity.Description;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="ModuleDTO"/> to an instance of <see cref="Module"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<Module> ToEntities(this IEnumerable<ModuleDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="Module"/> to an instance of <see cref="ModuleDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<ModuleDTO> ToDTOs(this IEnumerable<Module> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
