//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace platform.ltsyazilim.com.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefVehicleTypes
    {
        public byte VehicleTypeId { get; set; }
        public string VehicleTypeName { get; set; }
        public decimal VehicleWidth { get; set; }
        public decimal VehicleLength { get; set; }
        public decimal VehicleHeight { get; set; }
        public decimal VehicleVolume { get; set; }
        public int VehicleDesi { get; set; }
        public int VehicleWeight { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
    }
}
