//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace platform.ltsyazilim.com.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapFirmToUser
    {
        public long MapId { get; set; }
        public int FirmId { get; set; }
        public int UserId { get; set; }
        public bool IsAdmin { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
