//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace platform.ltsyazilim.com.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetails
    {
        public long OrderDetailId { get; set; }
        public long OrderRouteId { get; set; }
        public byte LoadProductPackageId { get; set; }
        public short LoadProductTypeId { get; set; }
        public int LoadProductWeight { get; set; }
        public decimal LoadProductVolume { get; set; }
        public decimal LoadProductVisibleVolume { get; set; }
        public byte LoadProductVolumeVisibleUnitId { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public bool OrderDetailType { get; set; }
    }
}
