//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace platform.ltsyazilim.com.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public long OrderId { get; set; }
        public int FirmId { get; set; }
        public int UserId { get; set; }
        public byte OrderTypeId { get; set; }
        public Nullable<byte> VehicleTypeId { get; set; }
        public Nullable<System.DateTime> DepartureDate { get; set; }
        public byte DepartureDateType { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public Nullable<byte> ArrivalDateType { get; set; }
        public string Comment { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
