//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace platform.ltsyazilim.com.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderRoutes
    {
        public long OrderRootId { get; set; }
        public Nullable<long> OrderId { get; set; }
        public Nullable<int> StartCountyId { get; set; }
        public Nullable<int> EndCountyId { get; set; }
    }
}
